spring:
    application:
        name: pizza-api
server:
    port: 8080
cxf:
    path: /api
    servlet.init:
        service-list-path: /info
    jaxrs:
        component-scan: true
        classes-scan-packages: org.apache.cxf.jaxrs.swagger,org.apache.cxf.metrics

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URI:http://localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2
        prefer-ip-address: true
        statusPageUrlPath: /api/info